datasets:
  task_name: "ynat"
model:
  model_name_or_path: "klue/bert-base"
trainer:
  max_seq_length: 64
  train_batch_size: 128
  eval_batch_size: 128
  cpkt_path: "ckpt"
  max_epochs: 10

hydra:  
  output_subdir: null  
  run:  
    dir: .
